swagger: '2.0'
info:
  description: RESTful API for Global ID service & Fintto Application
  version: 0.0.1
  title: Global ID service/Fintto RESTful Server
host: to.be.defined
basePath: /v1
tags:
  - name: gid
    description: APIs for GID service
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: fintto
    description: Operations about fintto service
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
schemes:
  - https
paths:
  /gid:
    post:
      tags:
        - gid
      summary: Add a new GID
      description: ''
      operationId: addGID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: GID object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/GID'
      responses:
        '405':
          description: Invalid input
    get:
      tags:
        - gid
      summary: Find GID by phone number
      description: ''
      operationId: getGIDByPhone
      produces:
        - application/json
      parameters:
        - in: query
          name: phone
          type: string
          required: true
          description: Hashed phone number to query
      responses:
        '200':
          description: '가입자의 경우 gid, 미가입자의 경우 “” 리턴'
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
              gid:
                type: string
                example: >-
                  08a4d1db1438ff353fa5e8b29830b4088377898568ca47a50eb7e386453e3aa8
        '500':
          description: Internal Server Errors
  '/gid/{GID}':
    get:
      tags:
        - gid
      summary: Query data by GID
      description: Returns a single GID data
      operationId: getGIDById
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: Global ID to return
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GID'
        '404':
          description: GID not found
    post:
      tags:
        - gid
      summary: Updates GID data
      description: ''
      operationId: updateGID
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: GID needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: GID data to be updated
          required: true
          schema:
            $ref: '#/definitions/GID'
      responses:
        '200':
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
          description: Update done
        '405':
          description: Invalid input
    delete:
      tags:
        - gid
      summary: Deletes a GID
      description: ''
      operationId: deleteGID
      produces:
        - application/json
      parameters:
        - name: api_key
          in: header
          required: false
          type: string
        - name: GID
          in: path
          description: GID to delete
          required: true
          type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
          description: Delete done
        '400':
          description: Invalid GID supplied
        '404':
          description: GID not found
  '/gid/{GID}/bank':
    post:
      tags:
        - fintto
      summary: Bank account registration
      description: This can only be done by the logged in user.
      operationId: registerBankAccont
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: GID to register a new bank account
          required: true
          type: string
        - in: body
          name: body
          description: Bank account information to register
          required: true
          schema:
            type: object
            properties:
              bankname:
                type: string
              account:
                type: string
              CI:
                type: string
              primary:
                type: boolean
                default: false
      responses:
        default:
          description: successful operation
    get:
      tags:
        - fintto
      summary: Get user's primary bank
      description: This can only be done by the logged in user.
      operationId: getPrimaryBank
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: GID to get primary bank
          required: true
          type: string
      responses:
        '200':
          description: |-
            User's primary bank.
            'bank' property will be null if the user has no registered bank.
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
              bank:
                type: string
                example: 한국은행
        '404':
          description: GID not found
  '/gid/{GID}/bank/{bankname}':
    delete:
      tags:
        - fintto
      summary: Delete user's bank account
      description: This can only be done by the logged in user.
      operationId: deleteBankAccount
      produces:
        - application/json
      parameters:
        - name: GID
          in: path
          description: GID to delete bank account
          required: true
          type: string
        - name: bankname
          in: path
          description: Bank name to be deleted
          required: true
          type: string
      responses:
        '200':
          schema:
            type: object
            properties:
              result:
                type: string
                example: Ok
          description: Bank account deleted
        '404':
          description: GID or bank not found
definitions:
  GID:
    type: object
    properties:
      gid:
        type: string
        format: 64byte
      username:
        type: string
      phone:
        type: string
      publicKey:
        type: string
        description: not used in current version
      userStatus:
        type: integer
        format: int32
        description: User Status
