definitions:
  Gid:
    type: string
    example: 08a4d1db1438ff353fa5e8b29830b4088377898568ca47a50eb7e386453e3aa8
    description: 글로벌 아이디
  Account:
    type: string
    example: "1403386939"
    description: 사용자의 은행계좌
  Password:
    type: string
    example: "6939"
    description: 은행계좌의 비밀번호
  Name:
    type: string
    example: 박현철
    description: 사용자 이름
  Phone:
    type: string
    example: "01032106939"
    description: 사용자의 전화번호
  Bank:
    type: string
    example: "shinhan"
    description: 은행명
  ReturnGid:
    type: object
    properties:
      result:
        type: string
        example: "OK"
        description: "성공 여부"
      gid:
        $ref: '#/definitions/Gid'
  Registration:
    type: object
    properties:
      gid:
        $ref: '#/definitions/Gid'
      name:
        $ref: '#/definitions/Name'
      phone:
        $ref: '#/definitions/Phone'
      email:
        type: string
        example: "fintto@samsung.com"
        description: "사용자의 email"
  DefaultResult:
    type: object
    properties:
      result:
        type: string
        example: "OK"
        description: "성공 여부"
      reason:
        type: string
        example: "0"
        description: "메시지 정보"
  BankRegistration:
    type: object
    properties:
      gid:
        $ref: '#/definitions/Gid'
      account:
        $ref: '#/definitions/Account'
      bank:
        $ref: '#/definitions/Bank'
      password:
        $ref: '#/definitions/Password'
  AccountCheck:
    type: object
    properties:
      gid:
        $ref: '#definitions/Gid'
      name:
        $ref: '#definitions/Name'
      account:
        $ref: '#/definitions/Account'
      password:
        $ref: '#/definitions/Password'
  AccountInfo:
    type: object
    properties:
      account:
        $ref: '#/definitions/Account'
      balance:
        type: string
        description: "계좌 잔액"
  TransferReq:
    type: object
    properties:
      send_gid:
        $ref: '#/definitions/Gid'
      account:
        $ref: '#/definitions/Account'
      transfer_amount:
        type: string
        example: "10000"
        description: "송금액"
      password:
        $ref: '#/definitions/Password'
      deposit_bank:
        $ref: '#/definitions/Bank'
      deposit_account:
        $ref: '#/definitions/Account'
  History:
    type: object
    properties:
      to:
        type: string
        description: "수신자의 계좌번호"
      from:
        type: string
        description: "송신자의 계좌번호"
      transfer:
        type: string
        description: "송금액수"
      time:
        type: string
        description: "거래시간"
